### ISSUE TITLE
Not able to use the package

### ISSUE THREAD

**Issue by Adbhavna1369** [cgobat/asymmetric_uncertainty#1]
Hi! I have been trying to use the package to implement it in my code, it keeps giving an error, I tried with jupyter notebooks, python and Google Collab. Please advise.

**Comment by Adbhavna1369** [comment]
![image](https://user-images.githubusercontent.com/73185067/187089707-50f04e7c-3696-4e7d-ae62-d76188df8658.png)
This is what I meant

It does install on my pc successfully, though, but I face a similar error

**Comment by Adbhavna1369** [comment]
![image](https://user-images.githubusercontent.com/73185067/187089918-8d6142fc-bb35-4851-9f7f-85787c95a9ff.png)

I faced something like this with Google Collab..

**Comment by cgobat** [comment]
This is expected behavior; the package is not indexed on PyPI, which is what pip uses by default. Have you tried following the installation instructions at the bottom of the [README](https://github.com/cgobat/asymmetric_uncertainty#readme)?

**Comment by cgobat** [comment]
I am going to mark this issue closed. If you have further trouble please feel free to respond here or open another issue.
