### ISSUE TITLE
PDF normalization.

### ISSUE THREAD

**Issue by mikemoss3** [cgobat/asymmetric_uncertainty#13]
The normalization of the piecewise Normal distribution was based on the Eq. 2 of [2008ApJ...672..433S](https://ui.adsabs.harvard.edu/abs/2008ApJ...672..433S/abstract) and/or Eq. 2.1 of [doi:10.1080/03610928208828279](https://doi.org/10.1080/03610928208828279). 

However, I do not believe the normalization is correct. If we test the integral of this function, we see that the integral of the currently implemented pdf() returns 2. Let's define a point at 200 with some asymmetric errors and then define a range of x values: 
```
datap = a_u(200,10,15)
neg_x = np.linspace(datap.value-(num_sigma*datap.minus),datap.value,discretization)
pos_x = np.linspace(datap.value,datap.value+(num_sigma*datap.minus),discretization)
x_arr = np.array(list(neg_x)+list(pos_x))
```
Then we find the PDF value at each point in `x_arr` using the equation currently implemented in pdf():
```
pdf = np.piecewise(x_arr, [x_arr<datap.value, x_arr>=datap.value],
	[lambda y : np.sqrt(2)/np.sqrt(np.pi)/(datap.plus+datap.minus) * np.exp(-1*(y-datap.value)**2 / (2*datap.minus**2)),
	lambda y : np.sqrt(2)/np.sqrt(np.pi)/(datap.plus+datap.minus) * np.exp(-1*(y-datap.value)**2 / (2*datap.plus**2))] ) 
```
We can take the sum of all the PDF values, but we also have to multiply by the size of each integration piece (i.e., Riemann-sum integration).   
```
delta = (x_arr[-1] - x_arr[0])/discretization
norm = np.sum( temp*delta )
```
`norm` will have a value of 2. This can be normalized if the `np.sqrt(2)` in the pdf variable definition are sent to the denominator (i.e., the same as dividing the whole thing by 2). 

Maybe I missed something in my test above?

**Comment by cgobat** [comment]
I just checked the following:

```python
from scipy.integrate import quad # function-based numeric integration/quadrature utility

p = a_u(200,10,15) # test value

integral, abserr = quad(p.pdf, p.value-(p.minus*6), p.value+(p.plus*6)) # arguments are (func, a, b)

print(integral) # outputs 0.9999999980336641
```

This seems like it's working as expected. Similarly, we could do

```python
from scipy.integrate import trapezoid # array-based numeric integration utility

datap = a_u(200,10,15)
num_sigma = 5
discretization = 500
neg_x = np.linspace(datap.value-(num_sigma*datap.minus),datap.value,discretization)
pos_x = np.linspace(datap.value,datap.value+(num_sigma*datap.plus),discretization) # I changed this line relative to your example from datap.minus to datap.plus
x_arr = np.array(list(neg_x)+list(pos_x))

pdf = np.piecewise(x_arr, [x_arr<datap.value, x_arr>=datap.value],
                   [lambda y : np.sqrt(2)/np.sqrt(np.pi)/(datap.plus+datap.minus) * np.exp(-1*(y-datap.value)**2 / (2*datap.minus**2)),
                    lambda y : np.sqrt(2)/np.sqrt(np.pi)/(datap.plus+datap.minus) * np.exp(-1*(y-datap.value)**2 / (2*datap.plus**2))] )

integral = trapezoid(y=pdf, x=x_arr)

print(integral) # outputs 0.9999999980259466
```

Upon confirming that it seems to be doing the right thing, I realized the issue: in your second-to-last line, you divide by `discretization` to compute `delta`. The evaluation of the PDF uses a total of `2*discretization` points, since there are `discretization` points both to the left and to the right of the nominal value. So there's the mystery factor of 2!
