### ISSUE TITLE
Support for np.exp function?

### ISSUE THREAD

**Issue by travisthieme** [cgobat/asymmetric_uncertainty#2]
Hi there~ really awesome package! 

I was just wondering if support could be added for the np.exp function? I just get:
`TypeError: loop of ufunc does not support argument 0 of type a_u which has no callable exp method`

My current workaround is to just use the Taylor series expansion of e^x, but that seems a bit unnecessary xD
Just wanted to ask first and see if it's possible! Thank you~

**Comment by cgobat** [comment]
Thanks for the suggestion, I'll look into this. In the meantime, another (perhaps easier) workaround you could try would be to manually raise $e$ to some power, i.e. `np.exp(1)**x`, if `x` is your instance of `a_u`.

**Comment by cgobat** [comment]
This functionality has been added. Please let me know if you try it out and have any comments.
