### ISSUE TITLE
PIP Install Doesn't work with latest version

### ISSUE THREAD

**Issue by sevenstarknight** [cgobat/asymmetric_uncertainty#6]
PIP's latest version (23.2.1.) won't install "pip install git+https://github.com/cgobat/asymmetric_uncertainty.git", you'll get a error that not all requirements have been met. But if you install 21.3.1., you get a successful installation.

**Comment by cgobat** [comment]
I figured out that this error has to do with the import order of packages, and I was able to replicate it using both pip 21.x and 23.x. I'm working on a fix, but in the meantime, just run `pip install numpy matplotlib` manually *prior* to running this module's installation, and that should resolve it.

**Comment by sevenstarknight** [comment]
> I figured out that this error has to do with the import order of packages, and I was able to replicate it using both pip 21.x and 23.x. I'm working on a fix, but in the meantime, just run `pip install numpy matplotlib` manually _prior_ to running this module's installation, and that should resolve it.

I will try it, thank you!
